In [ ]:
# to install or excute any command simply ou need to add ! mark in the first in the command line
# !pip install numpy
import numpy as np

In [9]:
array = np.random.randint(1, 10, size=10)
array

array([7, 6, 7, 7, 8, 7, 7, 3, 5, 3], dtype=int32)

In [26]:
# 1D array
# we can create array using np.array() or np.arange() methods
# np.arrange(start, end, skip value)

array = np.array([1 , 2, 3, 4])
array = np.arange(1, 5)


In [31]:
# Shape of an numpy array R*C
# (4,) means 1D array
array.shape
new_array = array.reshape(1, 4)
new_array.shape

[1 2 3 4]


In [40]:
# Heres the 2D array
arr = np.arange(1, 10).reshape(3, 3)
arr1 = np.arange(0, 10, 2).reshape(5, 1)
arr,  arr1
# for row in arr:
#     print(row)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[0],
        [2],
        [4],
        [6],
        [8]]))

In [46]:
np.ones((3, 4))
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# identify matrix
identity_matrix = np.eye(5)

In [62]:
identity_matrix.shape

identity_matrix.size
# identity_matrix.itemset

25

In [72]:
# vectorization here
arr1 = np.array([1, 2, 3, 4, 5])  # 1D array with sequential integers
arr2 = np.array([10, 20, 30, 40, 50])  # 1D array with multiples of 10
arr3 = np.array([3.5, 4.2, 5.8, 6.1])  # 1D array with float values
arr4 = np.array([0, -1, -2, -3, -4])  # 1D array with negative integers
arr5 = np.array([2, 4, 6, 8, 10, 12, 14])  # 1D array with even numbers


arr1 + arr2
arr2 - arr1
arr1.dot(arr2)

np.int64(550)

In [76]:
np.sqrt(arr1)
np.exp(arr1)
np.sin(arr1)
np.log(arr)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [81]:
# Normalization or standard normal distribution
data  = np.array([1, 2, 3, 4, 5, 6])

# calculate the sum
mean = np.mean(data)

# standar deviation
std_dev = np.std(data)

normalized_data = (data - mean) / std_dev
normalized_data

array([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007,
        1.46385011])

In [89]:
# Statistical methods
data  = np.array([1, 2, 3, 4, 5, 6])
me = np.mean(data)
mid = np.median(data)
# mo = np.mod(data, 2)
sd = np.std(data)
va = np.var(data)


me, mid, sd, va

(np.float64(3.5),
 np.float64(3.5),
 np.float64(1.707825127659933),
 np.float64(2.9166666666666665))

In [95]:
# logical operations
data > 4
# data[data > 4 and data%2==0]

data[(data > 4) & (data % 2 == 0)]
# print(result)

array([6])